ARG RUBY_VERSION
FROM ruby:$RUBY_VERSION

RUN curl -sL https://deb.nodesource.com/setup_6.x | bash - && \
  curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
  echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

RUN gem install bundler

RUN apt-get update -qq && apt-get upgrade -y && \
    apt-get install --no-install-recommends -y libpq-dev nodejs yarn

# Set an environment variable where the Rails app is installed to inside of Docker image

ENV RAILS_ROOT /var/www/escadra
RUN mkdir -p $RAILS_ROOT

# Set working directory
WORKDIR $RAILS_ROOT

COPY package.json yarn.lock $RAILS_ROOT/
RUN yarn install

# Setting env up
ENV RAILS_ENV='production'
ENV RACK_ENV='production'

# Adding gems
COPY Gemfile Gemfile
COPY Gemfile.lock Gemfile.lock
COPY .ruby-version .ruby-version

RUN bundle install --jobs 20 --retry 5 --without development test

# Adding project files
COPY . .
RUN bundle exec rake assets:precompile

EXPOSE 3000

CMD ["bundle", "exec", "puma", "-C", "config/puma.rb"]