default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: escadra_development

test:
  <<: *default
  database: escadra_test

production:
  <<: *default
  host: db
  username: postgres
  password:
  database: escadra_prod
